### PR TITLE
Adding `swnt new culture` command

### PR DESCRIPTION
**Pull request by jeremyf**
Exposing a means of rendering a random Culture on the command line.

(Also this is amongst my first Go lang code so please help me understand
if there is a better or more preferred approach)

### CODE REVIEW

**Review by nboughton — APPROVED** [review]
Whilst I'm not sure it's necessary to add a String function to Culture as the underlying type is already a string I don't see a problem with this change as it does mean that Culture now satisfies the stringer interface.

**Comment by jeremyf** [comment]
@nboughton Yeah…I was wondering about the `String()` function, as it looked like a bit of indirection. However, if it delivers on an interface (e.g. stringer), then all the better.

**Comment by nboughton** [comment]
I'm going to commit a slight change that removes the bytes import as returning Culture as a string only really requires one line: return string(Culture)

**Comment by jeremyf** [comment]
@nboughton I'll look over that commit and review the diff. Thanks for the follow-up. My next plan, if I find time, is to create the tables for Society.

**Comment by nboughton** [comment]
I previously had Society but as that content is part of the Deluxe edition I excluded it from the published code. I don't think it's fair to Kevin Crawford to include material that he explicitly charges for.

**Comment by jeremyf** [comment]
@nboughton As I hit enter, I thought "Right, those are in Revised Deluxe". I'm wondering about exposing an end-point that loads from a JSON document (which is up to you the owner to provide).

**Comment by nboughton** [comment]
In theory that would work but you would need to integrate configuring the end point in a non-intrusive way for the user. Having to run swnt -json /path/to/file (or whatever) to load on run time would be tiresome. 

You could use the default configuration options provided by cobra (~/.swnt.yaml) and Viper but you have to shoulder the overhead of working out how you want to pull in configuration options from there that don't mess with CLI defined arguments (which by definition have defaults). 

It's perfectly possible to do, it just requires working out the least inconvenient way to do it ;)

**Pull request merged**
